apiVersion: v1
kind: ConfigMap
metadata:
  name: checkpointer-config
  namespace: kube-system
data:
  KUBELET_ALLOW_INSECURE: "true" # Remove in case kubelet is serving a valid certificate (not self-signed)
  CHECKPOINT_IMAGE_PREFIX: "pbaran555/kaniko-checkpointed"
