apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: checkpointer
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: checkpointer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: checkpointer
    spec:
      serviceAccountName: pod-api-access
      containers:
        - name: checkpointer
          image: pbaran555/checkpointer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
          env:
            - name: CHECKPOINTER_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CHECKPOINTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CHECKPOINTER_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          envFrom:
            - configMapRef:
                name: checkpointer-config
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: checkpoints-tar-dir
              mountPath: /var/lib/kubelet/checkpoints
            ## Uncomment when using Kaniko File system strategy so that Checkpointer can share build context with Kaniko.
#            - name: build-contexts-dir
#              mountPath: /tmp/build-contexts

            ## Uncomment to preserve checkpoint results across Checkpointer restarts.
#            - name: storage-dir
#              mountPath: /checkpointer/storage
            - name: kubelet-tls-secret
              mountPath: /etc/kubernetes/tls
              readOnly: true
      volumes:
        - name: checkpoints-tar-dir
          hostPath:
            path: /var/lib/kubelet/checkpoints
         ## Uncomment when using Kaniko File system strategy so that Checkpointer can share build context with Kaniko.
#        - name: build-contexts-dir ### Can be uncommented to in case using
#          hostPath:
#            type: DirectoryOrCreate
#            path: /tmp/checkpointer/build-contexts

        ## Uncomment to preserve checkpoint results across Checkpointer restarts.
#        - name: storage-dir
#          hostPath:
#            type: DirectoryOrCreate
#            path: /tmp/checkpointer/storage
        - name: kubelet-tls-secret
          secret:
            secretName: kubelet-tls-secret
