apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-api-access
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checkpointer-pod-access-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  - apiGroups: [""] # Can be omitted if using Kaniko stdin strategy.
    resources: ["pods/attach"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-api-access-binding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: pod-api-access
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: checkpointer-pod-access-role
  apiGroup: rbac.authorization.k8s.io
