apiVersion: v1
kind: Service
metadata:
  name: checkpoint-service
  namespace: kube-system
spec:
# Uncomment to expose the service outside the cluster.
#  type: NodePort
  selector:
    app.kubernetes.io/name: checkpointer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3333
