# This file can update the JupyterHub Helm chart's default configuration values.

singleuser:
  cmd:
    - "jupyterhub-singleuser"               # Jupyter Notebook signs notebooks and stores the signatures in sqlite DB file.
    - "--NotebookNotary.db_file=':memory:'" # This options tell it to have the DB in memory, which an issues that upon, restore
  memory:                                   # Jupyter Notebook would fail to open the saved notebooks,
    limit: 500M
    guarantee: 500M
  storage:
    type: none # allows deploying the Jupyter Notebook containers without PersistentVolume
  image:
    name: quay.io/jupyter/base-notebook
    tag: latest
hub:
  image:
    pullPolicy: Always
    name: "pbaran555/hub-checkpoint-spawner" # a container which has access to CheckpointSpawner is set
    tag: "1.0.0"
  db:
    type: "sqlite-memory" # allows deploying the Hub container without PersistentVolume
  config:
    JupyterHub:
      spawner_class: "checkpoint-spawner.CheckpointSpawner" # tell Hub to use CheckpointSpawner as Spawner
      admin_users: # setup one admin user, jovyan1 has no meaning it is just historically used
        - jovyan1
