apiVersion: v1
kind: ConfigMap
metadata:
  name: checkpointer-cm
  namespace: kube-system
data:
  KUBELET_PORT: "10250"
  KUBELET_CERT_FILE: "/etc/kubernetes/pki/apiserver-kubelet-client.crt"
  KUBELET_CERT_KEY: "/etc/kubernetes/pki/apiserver-kubelet-client.key"
  CHECKPOINT_BASE_IMAGE: "pbaran555/checkpoint-base"