apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: checkpointer
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: checkpointer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: checkpointer
    spec:
      serviceAccountName: pod-api-access
      hostNetwork: true
      containers:
        - name: checkpointer
          image: pbaran555/checkpointer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PROXY_FORWARD
              value: "true"
          envFrom:
            - secretRef:
                name: container-registry-credentials
            - configMapRef:
                name: checkpointer-cm
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: checkpoints-tar-dir
              mountPath: /var/lib/kubelet/checkpoints
            - name: build-contexts-dir
              mountPath: /tmp/build-contexts
            - name: cert-dir
              mountPath: /etc/kubernetes/pki
      volumes:
        - name: checkpoints-tar-dir
          hostPath:
            path: /var/lib/kubelet/checkpoints
        - name: build-contexts-dir
          hostPath:
            type: DirectoryOrCreate
            path: /tmp/build-contexts
        - name: cert-dir
          hostPath:
            path: /etc/kubernetes/pki
